#!/bin/bash

echo "🚀 GUIDE DE TEST RAPIDE - Mireb CRM avec IA"
echo "============================================"
echo ""
echo "📋 Ce guide vous aide à tester rapidement les nouvelles fonctionnalités IA"
echo ""

# Couleurs
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🎯 ÉTAPES DE TEST :${NC}"
echo "=================="
echo ""
echo -e "${GREEN}1. Ouvrir l'application principale${NC}"
echo "   📁 Fichier: mireb-ai-crm-complete.html"
echo "   🌐 URL: https://franklin-mireb.github.io/mireb-/"
echo ""
echo -e "${GREEN}2. Se connecter comme Admin${NC}"
echo "   👤 Email: admin@mireb.com"
echo "   🔑 Password: admin123"
echo ""
echo -e "${GREEN}3. Aller dans la section Produits${NC}"
echo "   📦 Cliquer sur 'Admin Produits' dans le menu"
echo ""
echo -e "${GREEN}4. Tester l'ajout d'un produit avec IA${NC}"
echo "   ✏️  Saisir le nom: 'Smartphone Galaxy Pro'"
echo "   💰 Prix: 899"
echo "   🏷️  Catégorie: Électronique"
echo "   📸 Ajouter une image (upload ou URL)"
echo "   🎯 Public cible: Jeunes (18-30 ans)"
echo "   🔧 Caractéristiques: '5G, Caméra 108MP, Écran OLED'"
echo ""
echo -e "${GREEN}5. Utiliser les fonctions IA${NC}"
echo "   🔍 Cliquer 'Analyser Image' (si image ajoutée)"
echo "   🎨 Cliquer 'Générer avec IA' pour la description"
echo "   💾 Sauvegarder le produit"
echo ""
echo -e "${GREEN}6. Tester la page de test IA (optionnel)${NC}"
echo "   📁 Ouvrir: test-openai-api.html"
echo "   🧪 Tester chaque fonctionnalité individuellement"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT:${NC}"
echo "==============="
echo "• Les fonctions IA utilisent des fallbacks intelligents"
echo "• Si OpenAI n'est pas configuré, des descriptions automatiques sont générées"
echo "• Tous les tests peuvent être effectués même sans clé OpenAI"
echo ""
echo -e "${BLUE}🔧 DÉPANNAGE:${NC}"
echo "============="
echo "• Si erreur de validation → Vérifier que nom et prix sont remplis"
echo "• Si upload échoue → Le fallback local se déclenche automatiquement"
echo "• Si IA ne fonctionne pas → Le système de fallback prend le relais"
echo ""
echo -e "${GREEN}📊 Vérification technique:${NC}"
bash check-ai-integration.sh | head -20
echo ""
echo -e "${GREEN}✅ PRÊT POUR LES TESTS !${NC}"
echo "========================"
